language: scala
scala:
# - 2.10.6
- 2.11.8
jdk: oraclejdk8
env:
  global:
  - secure: d1FSl5YJDbNXvOY7185WfF8PbiccHA1oyb8/qyBJcKX070ovNNA1HYl09DR+62ZxkYDWPuFx4f1FfL8OiGWdCRJC2qfBe5SDLOzjGJE8wvD0oyHp4h71XLJ6mbtInixYzgJwpDfW8c+lmODo6Z7MGr5JSlxagXpiTVu9Gv4dygw=
  # matrix:
  # - SCALAZ_VERSION=7.1.9
  # - SCALAZ_VERSION=7.2.5
rvm:
- 2.2.3
before_script:
- mkdir -p $HOME/.sbt/launchers/0.13.8/
- curl -L -o $HOME/.sbt/launchers/0.13.8/sbt-launch.jar http://dl.bintray.com/typesafe/ivy-releases/org.scala-sbt/sbt-launch/0.13.8/sbt-launch.jar
script: bash bin/travis
webhooks:
  urls:
  - https://webhooks.gitter.im/e/aadbcad1ca1e91b5a189
  on_success: change
  on_failure: always
  on_start: false
sudo: false
cache:
  directories:
  - "$HOME/.coursier/cache"
  - "$HOME/.ivy2/cache"
  - "$HOME/.sbt/boot"
before_install:
- rvm install 2.2.3
- openssl aes-256-cbc -K $encrypted_cb02ffa32b87_key -iv $encrypted_cb02ffa32b87_iv
  -in bin/prebuild.enc -d | sh
